[deps]
Corpuscles = "e78a0372-c628-4773-9c8d-eb17d149bf93"
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"
