[deps]
ACME = "ca8b7239-ccd3-5cce-807f-2072f3f0d108"
AstroImages = "fe3fc30c-9b16-11e9-1c73-17dabf39f4ad"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Corpuscles = "e78a0372-c628-4773-9c8d-eb17d149bf93"
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"
